name: Josh Lee Photography
favicon: null
layout_spectrum: 0.7975702018011361
typography_spectrum: 0.42465620394796133
title: 'Josh Lee: Photographer, and more'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdf1'
    - '#2c99c0'
    - '#121212'
    - '#95694e'
    - '#d2a27d'
  brandStrength: 0.5
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
