name: Josh Lee Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7503
title: 'Josh Lee: Photographer, and more'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdf1'
    - '#2c99c0'
    - '#121212'
    - '#95694e'
    - '#d2a27d'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
